### ISSUE TITLE
fail to parse time in "config get"

### ISSUE THREAD

**Issue by meekworth** [meekworth/pylwdrone#2]
(Mentioned first in Issue 1, copying over to a new issue to track that.)

```Traceback (most recent call last):
  File "/home/user/.local/bin/pylwdrone", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/pylwdrone/__main__.py", line 25, in main
    ret = args.func(drone, args)
  File "/home/user/.local/lib/python3.9/site-packages/pylwdrone/__main__.py", line 87, in _cmd_config_get
    config = drone.get_config()
  File "/home/user/.local/lib/python3.9/site-packages/pylwdrone/lwdrone.py", line 79, in get_config
    return Config.from_bytes(rcmd.body)
  File "/home/user/.local/lib/python3.9/site-packages/pylwdrone/responses.py", line 139, in from_bytes
    conf._time = datetime.datetime.fromtimestamp(time)
OverflowError: timestamp out of range for platform time_t
```
"timestamp is 18446744073709523015"

"Version:        V300"

@grote, could I get a pcap of you trying to run "pylwdrone config get"? That would help to see what exactly is getting returned.

**Comment by grote** [comment]
I logged the `data` as a hex string in the response `Config#from_bytes(data)` method as that's easier:

`240000000000000000000000000000000000000000000000000000000000000000000031323334353637380000000000000000000000000000000000000000000000003790ffffffffffff0000000000000000000000000000000000563330300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

Let me know, if you still need a full pcap.
